set_1 = set()
set_2 = set()
set_1.update({7,8,9,1,2,3,4,5,0})
print(set_1)
set_2.update({4,5,6,0})
print(set_2)
subset = set_1.issubset(set_2)
print(subset)
element = set_1.intersection(set_2)
print(element)
rem = set_1.remove(8)
print(rem)
#rem1 = set_2.remove(8)
dis = set_1.discard(0)
dis1 = set_2.discard(0)
print(dis)
print(dis1)
union = set_1.union(set_2)
print(union)